#!/usr/bin/env bash
# First-run preparation. Safe to re-run. Then: docker compose up -d
set -euo pipefail
cd "$(dirname "$0")"
fail() { echo "✗ $*" >&2; exit 1; }
ok()   { echo "✓ $*"; }

# Host support
[[ -e /dev/kvm ]] || fail "/dev/kvm missing: enable virtualisation (VT-x/AMD-V) in BIOS, or nested virtualisation on a cloud VM"
[[ "$(uname -m)" == "x86_64" ]] || fail "dockur/windows and Edge for Linux need an amd64 host"
ok "KVM available"

# Secrets
[[ -f .env ]] || fail ".env missing: cp .env.example .env and set the passwords"
set -a; source .env; set +a
for v in WIN_USER WIN_PASSWORD GUAC_DB_PASSWORD GUAC_DB_ROOT_PASSWORD; do
  [[ -n "${!v:-}" && "${!v}" != change-me* ]] || fail "$v not set in .env"
done
ok ".env complete"

# Windows ISO (VMs sit on internal networks and cannot download it themselves)
[[ -f isos/windows.iso ]] || fail "isos/windows.iso missing: download the Windows 11 ISO from Microsoft and save it there"
ok "ISO present ($(du -h isos/windows.iso | cut -f1))"

# MCP firewall auth map (shared with ../mcp-firewall)
[[ -f ../mcp-firewall/config/auth-map.json ]] || fail "../mcp-firewall/config/auth-map.json missing: see ../mcp-firewall/README.md step 1-2"
ok "MCP auth map present"

# Guacamole schema, generated by the image that will read it
if [[ ! -s guacamole/01-initdb.sql ]]; then
  docker run --rm guacamole/guacamole:1.5.5 /opt/guacamole/bin/initdb.sh --mysql > guacamole/01-initdb.sql
fi
ok "Guacamole schema ready"

# Per-VM OEM folders: name -> that VM's egress proxy IP (must match docker-compose.yml)
declare -A VMS=( [app-a]=172.31.11.2 [app-b]=172.31.12.2 )
for vm in "${!VMS[@]}"; do
  ./make-oem.sh "$vm" "${VMS[$vm]}"
  mkdir -p "vms/$vm" "shared/$vm"
done
mkdir -p mcp-output

echo
echo "Ready. Start with: docker compose up -d"
echo "Watch first install (10-30 min per VM): docker compose logs -f app-a"
echo "Then open http://localhost:8080 (guacadmin / guacadmin, change it at once)"
